env:
  browser: true
  commonjs: true
  es6: true
extends:
  - airbnb
  - prettier
  - prettier/react
parserOptions:
  ecmaVersion: 2020
rules:
  prettier/prettier:
    - error
    - trailingComma: es5
      singleQuote: true
      printWidth: 120
      endOfLine: auto
  semi: [error, always]
  quotes: [error, single]
  one-var: 0
  no-console: 0
  max-nested-callbacks: [error, 3]
  max-params: [error, 8]
  max-depth: [error, 5]
  max-lines-per-function: [error, 80]
  complexity: [error, 8]
  class-methods-use-this: 0
  react/jsx-filename-extension: 0
  jsx-a11y/label-has-associated-control:
    - error
    - required:
      some: [nesting, id]
  react/prop-types: 0
  react/jsx-props-no-spreading: 0
plugins:
  - prettier
